export type Product={id:string;name:string;image:number;category:string;price:number;url:string;subtitle:{fr:string;en:string};description:{fr:string;en:string};materials:{fr:string;en:string}};
export const categoryNames:Record<string,{fr:string;en:string}>={all:{fr:'Tous les bijoux',en:'All jewelry'},earrings:{fr:'Boucles d’oreilles',en:'Earrings'},necklaces:{fr:'Colliers',en:'Necklaces'},sets:{fr:'Parures',en:'Jewelry sets'},pendants:{fr:'Pendentifs',en:'Pendants'}};
const rows=[
['9998134444','Éclat',1,'sets',14,'Parure · pierres multicolores','Jewelry set · multicolored stones','Une rencontre de rouge, de vert profond et de nuances minérales. Un collier et ses boucles d’oreilles assorties pour une touche de couleur délicate.','A meeting of red, deep green and mineral shades. A necklace and matching earrings for a delicate touch of color.','Pierres naturelles multicolores. Montage et chaîne de couleur argentée. Collier et paire de boucles d’oreilles inclus.','Multicolored natural stones. Silver-colored wire and chain. Includes necklace and a pair of earrings.'],
['9993758147','Bleu de nuit',2,'earrings',12,'Boucles longues · pierres & cristal','Long earrings · stones & crystal','Des nuances de bleu nuit et de blanc, prolongées par une pierre transparente. Une ligne élancée et un montage argenté réalisé à la main.','Midnight blue and white shades, finished with a transparent stone. An elongated silhouette with handmade silver-colored wirework.','Pierres naturelles bleues, bleu-gris et blanches, pierre transparente à la base. Fil et crochets de couleur argentée.','Blue, blue-gray and white natural stones, with a transparent stone at the base. Silver-colored wire and hooks.'],
['9266144463','Nuance',3,'necklaces',17,'Collier · agate du Botswana','Necklace · Botswana agate','L’agate du Botswana se dévoile dans un collier fait main, aux nuances profondes et au caractère singulier.','Botswana agate takes center stage in a handmade necklace with deep tones and an individual character.','Agate du Botswana. Création artisanale. Pour les dimensions et les détails du montage, consultez l’annonce ou contactez la créatrice.','Botswana agate. Handmade. For measurements and construction details, check the listing or contact the maker.'],
['9266036025','Harmonie',4,'necklaces',15,'Collier · pierres naturelles & acier','Necklace · natural stones & steel','Un collier en pierres naturelles et acier inoxydable, assemblé à la main. Des nuances à découvrir de près.','A handmade necklace combining natural stones and stainless steel. Discover its shades up close.','Pierres naturelles et acier inoxydable, selon l’annonce. Dimensions et nature précise des pierres à confirmer auprès de la créatrice.','Natural stones and stainless steel, as listed. Confirm dimensions and exact stone types with the maker.'],
['8183785770','Clarté',5,'earrings',7,'Boucles · cristal & jade blanc','Earrings · crystal & white jade','Le cristal et le jade blanc, délicatement entourés de fil métallique. Une paire lumineuse, façonnée en wire wrapping.','Crystal and white jade, delicately wrapped in jewelry wire. A luminous pair shaped by hand.','Cristal et jade blanc. Fil métallique de création BENECREAT. De légères asymétries sont propres au travail artisanal.','Crystal and white jade. BENECREAT jewelry wire. Small asymmetries are part of the handmade work.'],
['8183753969','Éclipse',6,'sets',7,'Parure · agate rayée','Jewelry set · striped agate','Les nuances de l’agate rayée rencontrent les courbes d’un fil doré. Un collier avec pendentif et ses boucles assorties.','Striped agate meets the curves of golden-colored wire. A pendant necklace and matching earrings.','Agate rayée, perles de 8 mm. Fil métallique de création BENECREAT, couleur dorée. Collier et boucles assorties.','Striped agate, 8 mm beads. Golden-colored BENECREAT jewelry wire. Necklace and matching earrings.'],
['8183728093','Soleil',7,'pendants',4,'Pendentif · esprit solaire','Pendant · a touch of sunshine','Un petit soleil à porter près de soi. Un pendentif façonné à la main, tout en courbes et en lumière.','A little sunshine to keep close. A handmade pendant with a curved, radiant design.','Pendentif vendu selon le contenu de l’annonce. Matières, dimensions et présence éventuelle d’une chaîne à confirmer auprès de la créatrice.','Pendant sold as described in the listing. Confirm materials, dimensions and whether a chain is included with the maker.'],
['8175538425','Aurore',8,'sets',8,'Parure · cornaline & jade blanc','Jewelry set · carnelian & white jade','La chaleur de la cornaline et la douceur du jade blanc se rencontrent dans une parure aux lignes dorées, façonnées à la main.','The warmth of carnelian meets the softness of white jade in a handmade set with golden-colored curves.','Cornaline et jade blanc. Fil métallique de création BENECREAT, couleur dorée. Collier avec pendentif et boucles assorties.','Carnelian and white jade. Golden-colored BENECREAT jewelry wire. Pendant necklace and matching earrings.']
];
export const products:Product[]=rows.map(r=>({id:r[0] as string,name:r[1] as string,image:r[2] as number,category:r[3] as string,price:r[4] as number,url:'https://www.vinted.fr/items/'+r[0],subtitle:{fr:r[5] as string,en:r[6] as string},description:{fr:r[7] as string,en:r[8] as string},materials:{fr:r[9] as string,en:r[10] as string}}));
